import { afterAll, beforeAll, describe, expect, test } from 'bun:test'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { hasGeneratedHeader, isGeneratedPath } from '../../src/core/queries/generated-code.js'

describe('isGeneratedPath', () => {
	test('matches gomock fake filenames', () => {
		expect(isGeneratedPath('internal/storage/fake_store.go')).toBe(true)
		expect(isGeneratedPath('fake_store.go')).toBe(true)
	})

	test('matches gomock mock filenames', () => {
		expect(isGeneratedPath('pkg/api/mock_client.go')).toBe(true)
		expect(isGeneratedPath('pkg/api/client_mock.go')).toBe(true)
	})

	test('matches mocks/, fakes/, and __generated__/ subdirectories', () => {
		expect(isGeneratedPath('services/user/mocks/user_service.go')).toBe(true)
		expect(isGeneratedPath('services/user/fakes/user_service.go')).toBe(true)
		expect(isGeneratedPath('web/client/__generated__/graphql.ts')).toBe(true)
	})

	test('does not match plain production files', () => {
		expect(isGeneratedPath('src/core/engine.ts')).toBe(false)
		expect(isGeneratedPath('pkg/api/client.go')).toBe(false)
		expect(isGeneratedPath('services/user/user_service.go')).toBe(false)
	})

	test('does not mis-match names that only contain fake/mock as a substring', () => {
		expect(isGeneratedPath('pkg/fakeness/real.go')).toBe(false)
		expect(isGeneratedPath('internal/mocking/util.go')).toBe(false)
	})
})

describe('hasGeneratedHeader', () => {
	let root: string

	beforeAll(() => {
		root = mkdtempSync(join(tmpdir(), 'atlas-gen-header-'))
	})

	afterAll(() => {
		rmSync(root, { recursive: true, force: true })
	})

	test('returns true for files with a "code generated" do-not-edit header', () => {
		const path = join(root, 'gomock.go')
		writeFileSync(
			path,
			`// Code generated by MockGen. DO NOT EDIT.\n\npackage fakes\n\nfunc X() {}\n`,
		)
		expect(hasGeneratedHeader(path)).toBe(true)
	})

	test('returns true for protoc-style headers', () => {
		const path = join(root, 'foo.pb.go')
		writeFileSync(
			path,
			`// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: foo.proto\n\npackage pb\n`,
		)
		expect(hasGeneratedHeader(path)).toBe(true)
	})

	test('returns false for hand-written files', () => {
		const path = join(root, 'handwritten.go')
		writeFileSync(path, `package main\n\nfunc main() {}\n`)
		expect(hasGeneratedHeader(path)).toBe(false)
	})

	test('returns false for missing files', () => {
		expect(hasGeneratedHeader(join(root, 'does-not-exist.go'))).toBe(false)
	})

	test('only scans the first 4kb', () => {
		const path = join(root, 'late-header.go')
		const padding = ' '.repeat(5000)
		writeFileSync(path, `package main\n${padding}\n// Code generated. DO NOT EDIT.\n`)
		expect(hasGeneratedHeader(path)).toBe(false)
	})
})
